// workflow-config.js
// ─────────────────────────────────────────────────────────────
// This is the ONLY file you change to swap scenarios.
// Everything else in Mission Control is generic.
// ─────────────────────────────────────────────────────────────

export const WORKFLOW = {

  // ── Identity ──────────────────────────────────────────────
  name:        'Codebase Health Audit',
  description: 'Scans a repository for test coverage gaps, dead code, security antipatterns, and vulnerable dependencies.',
  inputLabel:  'Repo / prompt',
  inputPlaceholder: 'e.g. github.com/user/repo\n\nOr describe the codebase to audit...',
  runLabel:    'Run Audit',
  reportTitle: 'Health Report',

  // ── Effort descriptions ───────────────────────────────────
  effortDesc: {
    low:    'Quick pass — ~20% file sampling, fast & cheap',
    medium: 'Balanced scan — ~40% file sampling',
    high:   '~90% sampling — thorough, higher cost',
  },

  // ── Planner (Orchestrator) ────────────────────────────────
  planner: {
    model: 'claude-opus-4-8',
    scriptTemplate: (effort, sample) => `\
// ── Orchestration plan ── generated by claude-opus-4-8
// Task: codebase health audit
// Effort: ${effort} · Sampling: ${sample}%

const AGENTS = [
  { id: 0, name: "Test Coverage",  model: "claude-haiku-4-5",  focus: "test files, coverage gaps"     },
  { id: 1, name: "Dead Code",      model: "claude-haiku-4-5",  focus: "unused exports, dead branches"  },
  { id: 2, name: "Security",       model: "claude-sonnet-4-6", focus: "secrets, injection vectors"     },
  { id: 3, name: "Dependencies",   model: "claude-haiku-4-5",  focus: "outdated, vulnerable packages"  },
];

// Fan-out — run all agents concurrently
const results = await Promise.allSettled(
  AGENTS.map(agent => runAgent(agent))
);

// Adversarial verification pass
const verified = await verifyFindings(results);

// Synthesize final report
return buildReport(verified);`,
  },

  // ── Scan agents ───────────────────────────────────────────
  agents: [
    {
      id: 0, name: 'Test Coverage', model: 'claude-haiku-4-5',
      color: 'var(--agent-0)', colorRgb: '14,165,233',
      description: 'Scans test files, measures coverage gaps',
      stream: [
        "→ scanning src/ for *.test.js, *.spec.ts ...",
        "→ found 24 test files across 3 modules",
        "→ auth/login.test.js — 38% coverage (threshold: 80%)",
        "→ api/payments.ts — 0 test files found",
        "→ utils/crypto.js — no unit tests",
        "⚠ 6 files below 60% coverage threshold",
        "✓ components/ fully covered (94% avg)",
        "→ compiling findings...",
      ],
      findings: [
        { sev:'high',   title:'api/payments.ts has zero test coverage',  desc:'Payments module handles real transactions with no test harness. Any regression goes undetected.' },
        { sev:'medium', title:'6 files below 60% coverage threshold',    desc:'auth/login, utils/crypto and 4 others fall below project threshold of 80%.' },
      ],
    },
    {
      id: 1, name: 'Dead Code', model: 'claude-haiku-4-5',
      color: 'var(--agent-1)', colorRgb: '167,139,250',
      description: 'Detects unused exports and dead branches',
      stream: [
        "→ parsing AST for export/import graph...",
        "→ building reference map across 87 files",
        "→ utils/legacy.js — exported but 0 imports",
        "→ helpers/formatDate.js — 3 unused functions",
        "→ config/deprecated.ts — entire file unreferenced",
        "→ scanning dead conditional branches...",
        "→ found 2 feature flags always-false in prod",
        "✓ scan complete — 11 dead symbols found",
      ],
      findings: [
        { sev:'low', title:'11 unused exports across 3 files',  desc:'utils/legacy.js and helpers/formatDate.js export symbols that are never imported.' },
        { sev:'low', title:'2 feature flags permanently false', desc:'config/flags.ts: ENABLE_NEW_CHECKOUT and BETA_API both always false in prod.' },
      ],
    },
    {
      id: 2, name: 'Security', model: 'claude-sonnet-4-6',
      color: 'var(--agent-2)', colorRgb: '244,114,182',
      description: 'Finds hardcoded secrets, injection vectors',
      stream: [
        "→ scanning for hardcoded credentials...",
        "→ ALERT: .env.example contains real API key",
        "→ ALERT: src/db/seed.js — password in plaintext",
        "→ scanning SQL query construction...",
        "→ api/users.js:142 — unsanitised user input",
        "→ checking dependency injection patterns...",
        "→ no XSS vectors found in template layer",
        "✓ 3 critical, 1 high severity findings",
      ],
      findings: [
        { sev:'critical', title:'Real API key committed in .env.example',  desc:'STRIPE_SECRET_KEY found with value sk_live_... — rotate immediately and purge from git history.' },
        { sev:'critical', title:'Plaintext password in db/seed.js',         desc:'Admin seed credentials are hardcoded on line 34. Should use environment variable.' },
        { sev:'high',     title:'SQL injection vector in api/users.js:142', desc:'User-supplied `id` param concatenated directly into query string without sanitisation.' },
      ],
    },
    {
      id: 3, name: 'Dependencies', model: 'claude-haiku-4-5',
      color: 'var(--agent-3)', colorRgb: '52,211,153',
      description: 'Audits outdated and vulnerable packages',
      stream: [
        "→ reading package.json — 47 dependencies",
        "→ querying npm audit...",
        "→ lodash@4.17.15 — known prototype pollution",
        "→ express@4.17.1 — 2 moderate CVEs",
        "→ 14 packages have patch updates available",
        "→ 3 packages abandoned (last commit > 2yr)",
        "→ checking license compatibility...",
        "✓ 1 critical CVE, 2 moderate, 17 outdated",
      ],
      findings: [
        { sev:'critical', title:'lodash@4.17.15 — prototype pollution CVE', desc:'CVE-2019-10744. Upgrade to 4.17.21. Affects _.merge and _.defaultsDeep with user input.' },
        { sev:'medium',   title:'14 packages have patch updates pending',   desc:'Minor version bumps available. Run npm audit fix to apply auto-fixable updates.' },
      ],
    },
  ],

  // ── Human review ─────────────────────────────────────────
  // In sim mode, this flag controls whether contested findings escalate to human.
  // In live mode, the planner sets this dynamically based on stakes.
  humanReviewOnContested: true,

  // ── Verifiers ─────────────────────────────────────────────
  // One entry per scan agent (same order).
  // Each entry is an array of passes.
  // verdict: 'confirmed' | 'amended' | 'contested' | 'refuted'
  verifiers: [
    // Verifier 0 — Test Coverage (2 passes — payments.ts contested, exhausts passes → human review)
    [
      { model:'claude-sonnet-4-6',
        lines:[
          "→ cross-checking coverage report vs CI config...",
          "→ payments.ts — no spec file found in repo",
          "✗ CONTEST: payments.ts may be tested via integration suite",
          "→ 6 low-coverage files confirmed against lcov.info",
          "⚠ payments.ts escalating to pass 2 — integration tests unverified",
        ],
        verdicts:[
          { index:0, verdict:'contested', reason:'Cannot confirm absence of integration test coverage without running CI pipeline.' },
          { index:1, verdict:'confirmed' },
        ],
      },
      { model:'claude-opus-4-8',
        lines:[
          "→ scanning CI config for integration test suites...",
          "→ found: cypress/ folder but no payments spec",
          "→ checked test:integration script — payments excluded",
          "✗ CONTEST: CI pipeline config is ambiguous — manual check required",
          "⚠ exhausted AI passes — escalating to human review",
        ],
        verdicts:[
          { index:0, verdict:'contested', reason:'CI config references a shared payments mock but actual coverage is unverifiable without running the suite. Human must check.' },
        ],
      },
    ],

    // Verifier 1 — Dead Code (1 pass, 1 amended)
    [{ model:'claude-sonnet-4-6',
       lines:[
         "→ checking dynamic imports for legacy.js...",
         "→ FOUND: require('./utils/legacy') in build/bundle.js",
         "→ 3 of 11 'unused' symbols used via dynamic import",
         "→ amending finding: dead count 11 → 8",
         "→ feature flags — confirmed always-false in env",
         "✓ 1 amended · 1 confirmed",
       ],
       verdicts:[
         { index:0, verdict:'amended', newDesc:'8 confirmed unused exports (3 were false positives via dynamic import in build/bundle.js).' },
         { index:1, verdict:'confirmed' },
       ],
    }],

    // Verifier 2 — Security (2 passes — seed.js contested, resolved by pass 2)
    [
      { model:'claude-sonnet-4-6',
        lines:[
          "→ fetching .env.example from git log --all...",
          "→ confirmed: sk_live_ key present in 4 commits",
          "→ SQL injection — reproducing on staging...",
          "→ payload injected — confirmed HIGH",
          "→ checking seed.js — test fixture or prod data?",
          "✗ CONTEST: seed.js may be test-only, not prod",
          "⚠ escalating seed.js to pass 2...",
        ],
        verdicts:[
          { index:0, verdict:'confirmed' },
          { index:2, verdict:'confirmed' },
          { index:1, verdict:'contested', reason:'seed.js could be a test fixture; cannot confirm prod exposure without checking Dockerfile.' },
        ],
      },
      { model:'claude-opus-4-8',
        lines:[
          "→ tracing seed.js through deploy pipeline...",
          "→ found: seed.js in Dockerfile COPY . /app",
          "→ seed.js confirmed in production container",
          "→ password is live and exploitable in prod",
          "✓ contested finding CONFIRMED — critical stands",
        ],
        verdicts:[
          { index:1, verdict:'confirmed' },
        ],
      },
    ],

    // Verifier 3 — Dependencies (2 passes — patch count still contested after pass 2 → human review)
    [
      { model:'claude-sonnet-4-6',
        lines:[
          "→ re-running npm audit --json...",
          "→ lodash CVE confirmed — package-lock matches",
          "→ checking patch count scope...",
          "✗ CONTEST: 14 may include devDeps not in prod",
          "⚠ escalating patch count to pass 2...",
        ],
        verdicts:[
          { index:0, verdict:'confirmed' },
          { index:1, verdict:'contested', reason:'Cannot determine exact prod vs dev split without access to deployment manifest.' },
        ],
      },
      { model:'claude-opus-4-8',
        lines:[
          "→ re-analyzing package.json structure...",
          "→ devDependencies list is non-standard — bundler config unclear",
          "→ webpack config bundles some devDeps into prod bundle",
          "✗ CONTEST: prod boundary is ambiguous — bundler must be inspected manually",
          "⚠ exhausted AI passes — escalating to human review",
        ],
        verdicts:[
          { index:1, verdict:'contested', reason:'Webpack config bundles marked devDependencies. Actual prod exposure requires human inspection of the bundle manifest.' },
        ],
      },
    ],
  ],

  // ── Synthesis ─────────────────────────────────────────────
  synthesis: {
    model: 'claude-opus-4-8',
    stream: [
      "→ collecting verified findings from all agents...",
      "→ deduplicating across agent boundaries...",
      "→ ranking by severity × exploitability...",
      "→ generating remediation priorities...",
      "→ cross-referencing findings for blast radius...",
      "✓ report synthesized",
    ],
  },

  // ── Sample scenarios shown in Help modal ─────────────────
  samples: [
    { icon:'🔍', title:'Codebase Health Audit',   desc:'Test coverage · Dead code · Security · Dependencies' },
    { icon:'📝', title:'Content Moderation',       desc:'Toxicity · Legal risk · Brand safety · Factual accuracy' },
    { icon:'👔', title:'Job Application Screener', desc:'Skills match · Culture fit · Experience gaps · Red flags' },
    { icon:'📊', title:'Market Research',          desc:'Competitor pricing · Reviews · Social sentiment · News' },
    { icon:'🏢', title:'Due Diligence',            desc:'Financials · Legal filings · News · LinkedIn signals' },
    { icon:'♿', title:'Code Review',              desc:'Performance · Accessibility · Security · Style guide' },
  ],
};
